#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 14 10:59:52 2021

@author: harry
"""

import numpy as np
import pandas as pd
from datetime import datetime

import gzip
import glob

import meteo_marine_traitement as mmt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

files_list=[]
files=glob.glob('/home/harry/Documents/projet_station_meteo/bouee marines/marine.201[4,5,6,8]*.csv.gz')

for filename in files:
   with gzip.open(filename) as f:
      data=pd.read_csv(f, sep=";")
      files_list.append(data)
    
data=pd.concat(files_list, axis=0)

meteo=mmt.Meteo_Marine_Classeur(data, jours=3)
dataset=meteo.data_good_shape
cible=meteo.target_force

X_train, X_test, y_train, y_test=train_test_split(dataset, cible, test_size=0.2)

model=RandomForestClassifier(n_jobs=2, n_estimators=150)
model.fit(X_train, y_train)

print(model.score(X_train, y_train))
print(model.score(X_test, y_test))
